name: flutter_translate_annotations
description: Defines the annotations used by flutter_translate_gen to create statically-typed localization keys.
version: 2.1.0
homepage: https://bratan.me
repository: https://github.com/celltrak/Flutter-Translate-Annotations

environment:
  sdk: '>=3.2.0 <4.0.0'
